### ISSUE TITLE
Use luna-dns port 53

### ISSUE THREAD

**Issue by Padandish** [r7wx/luna-dns#2]
Hi dear,
I use the Ubuntu operating system. I have disabled systemd-resolved service.
When I run the program on port 53 from the command line. everything all right.
But when I want to run the program as a service, it cannot be activated on port 53.

**Comment by r7wx** [comment]
Hi,
Does not sounds like an issue related to luna-dns. How are you executing it as service? Are you sure you are executing it with root user (to have permission to bind on port 53)?
